### ISSUE TITLE
Error opening the app

### ISSUE THREAD

**Issue by bouthouri** [Oussema-Ben-Dahmen/ChitChat#7]
I have this error when opening the app.

```internal/modules/cjs/loader.js:807
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/oussama/work/candidats/ChitChat/Back-End/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node, 1): no suitable image found.  Did find:
        /Users/oussama/work/candidats/ChitChat/Back-End/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
        /Users/oussama/work/candidats/ChitChat/Back-End/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/oussama/work/candidats/ChitChat/Back-End/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/oussama/work/candidats/ChitChat/Back-End/helpers/PasswordHasher/index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
[nodemon] app crashed - waiting for file changes before starting...```

**Comment by OussemaBenDahmen** [comment]
Hello,

I spent some time testing the application on a different laptop and as I
was cloning the repository on the device i noticed that i mistakenly
uploaded the node_module folder as well as the project files, hence there
was a problem with the bcrypt module.

I also had some research on that topic in which I found people suggesting
manually uninstalling the modules and reinstalling them .

as it's shown in the link :
https://stackoverflow.com/questions/32366903/node-modules-bcrypt-node-modules-bindings-bindings-js83


I am deeply sorry for the inconvenience. I think it was all caused by the
upload of the nodes_module folder due to it not being included in the
.gitignore file.

I fixed that problem on the github repository and it should be good now .

Also I changed the Mongodb URI too.


and now for the application to run correctly delete the local repository on
your device, clone it again and follow the steps in the README file.

I hope that nothing goes wrong and you can contact me if any other bugs
present themselves in the future



sincerely,
Oussema Ben Dahmen
